// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppCorpDbContext))]
    partial class AppCorpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataAccessLayer.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MessageSent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MessagesLog");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhoneNumber = "1686041828299",
                            UserName = "Chaim"
                        },
                        new
                        {
                            Id = 2,
                            PhoneNumber = "1621042619399",
                            UserName = "Tatum"
                        },
                        new
                        {
                            Id = 3,
                            PhoneNumber = "1620110657599",
                            UserName = "Melinda"
                        },
                        new
                        {
                            Id = 4,
                            PhoneNumber = "1683040258999",
                            UserName = "Eve"
                        },
                        new
                        {
                            Id = 5,
                            PhoneNumber = "1640010419899",
                            UserName = "Ezekiel"
                        },
                        new
                        {
                            Id = 6,
                            PhoneNumber = "1683092404299",
                            UserName = "Yen"
                        },
                        new
                        {
                            Id = 7,
                            PhoneNumber = "1675042471999",
                            UserName = "Rhona"
                        },
                        new
                        {
                            Id = 8,
                            PhoneNumber = "1631112326699",
                            UserName = "Casey"
                        },
                        new
                        {
                            Id = 9,
                            PhoneNumber = "1626022029399",
                            UserName = "Ulric"
                        },
                        new
                        {
                            Id = 10,
                            PhoneNumber = "1694013052899",
                            UserName = "Darius"
                        },
                        new
                        {
                            Id = 11,
                            PhoneNumber = "1689040276999",
                            UserName = "Felicia"
                        },
                        new
                        {
                            Id = 12,
                            PhoneNumber = "1633090464799",
                            UserName = "Noel"
                        },
                        new
                        {
                            Id = 13,
                            PhoneNumber = "1618021320899",
                            UserName = "Amber"
                        },
                        new
                        {
                            Id = 14,
                            PhoneNumber = "1628060984499",
                            UserName = "Hedwig"
                        },
                        new
                        {
                            Id = 15,
                            PhoneNumber = "1688090345099",
                            UserName = "Briar"
                        },
                        new
                        {
                            Id = 16,
                            PhoneNumber = "1643031884399",
                            UserName = "Kylee"
                        },
                        new
                        {
                            Id = 17,
                            PhoneNumber = "1698120710899",
                            UserName = "Xerxes"
                        },
                        new
                        {
                            Id = 18,
                            PhoneNumber = "1690021888699",
                            UserName = "Rosalyn"
                        },
                        new
                        {
                            Id = 19,
                            PhoneNumber = "1678070360199",
                            UserName = "Philip"
                        },
                        new
                        {
                            Id = 20,
                            PhoneNumber = "1655011943599",
                            UserName = "Beau"
                        },
                        new
                        {
                            Id = 21,
                            PhoneNumber = "1646042511299",
                            UserName = "Xavier"
                        },
                        new
                        {
                            Id = 22,
                            PhoneNumber = "1640092078999",
                            UserName = "Noel"
                        },
                        new
                        {
                            Id = 23,
                            PhoneNumber = "1666092029499",
                            UserName = "Charity"
                        },
                        new
                        {
                            Id = 24,
                            PhoneNumber = "1656082580499",
                            UserName = "Rajah"
                        },
                        new
                        {
                            Id = 25,
                            PhoneNumber = "1660072305099",
                            UserName = "Yen"
                        },
                        new
                        {
                            Id = 26,
                            PhoneNumber = "1682112931599",
                            UserName = "Benedict"
                        },
                        new
                        {
                            Id = 27,
                            PhoneNumber = "1610062842199",
                            UserName = "Paul"
                        },
                        new
                        {
                            Id = 28,
                            PhoneNumber = "1628043095099",
                            UserName = "Meghan"
                        },
                        new
                        {
                            Id = 29,
                            PhoneNumber = "1688082441099",
                            UserName = "Curran"
                        },
                        new
                        {
                            Id = 30,
                            PhoneNumber = "1648110402799",
                            UserName = "Burke"
                        },
                        new
                        {
                            Id = 31,
                            PhoneNumber = "1629060595999",
                            UserName = "Camden"
                        },
                        new
                        {
                            Id = 32,
                            PhoneNumber = "1656022704199",
                            UserName = "Cora"
                        },
                        new
                        {
                            Id = 33,
                            PhoneNumber = "1699081251099",
                            UserName = "Georgia"
                        },
                        new
                        {
                            Id = 34,
                            PhoneNumber = "1687051911799",
                            UserName = "Renee"
                        },
                        new
                        {
                            Id = 35,
                            PhoneNumber = "1655030180799",
                            UserName = "Ishmael"
                        },
                        new
                        {
                            Id = 36,
                            PhoneNumber = "1656101467799",
                            UserName = "Fiona"
                        },
                        new
                        {
                            Id = 37,
                            PhoneNumber = "1639011847399",
                            UserName = "Elvis"
                        },
                        new
                        {
                            Id = 38,
                            PhoneNumber = "1621010512399",
                            UserName = "Aimee"
                        },
                        new
                        {
                            Id = 39,
                            PhoneNumber = "1677080330899",
                            UserName = "Harriet"
                        },
                        new
                        {
                            Id = 40,
                            PhoneNumber = "1653102220299",
                            UserName = "Wynter"
                        },
                        new
                        {
                            Id = 41,
                            PhoneNumber = "1663060563299",
                            UserName = "Hedy"
                        },
                        new
                        {
                            Id = 42,
                            PhoneNumber = "1648061757099",
                            UserName = "Rina"
                        },
                        new
                        {
                            Id = 43,
                            PhoneNumber = "1671042978499",
                            UserName = "Patricia"
                        },
                        new
                        {
                            Id = 44,
                            PhoneNumber = "1694022010199",
                            UserName = "Merritt"
                        },
                        new
                        {
                            Id = 45,
                            PhoneNumber = "1615021666899",
                            UserName = "Yael"
                        },
                        new
                        {
                            Id = 46,
                            PhoneNumber = "1682052202099",
                            UserName = "Daniel"
                        },
                        new
                        {
                            Id = 47,
                            PhoneNumber = "1680012484699",
                            UserName = "Maya"
                        },
                        new
                        {
                            Id = 48,
                            PhoneNumber = "1633052726899",
                            UserName = "Unity"
                        },
                        new
                        {
                            Id = 49,
                            PhoneNumber = "1638121187699",
                            UserName = "Odette"
                        },
                        new
                        {
                            Id = 50,
                            PhoneNumber = "1609030736099",
                            UserName = "Ivana"
                        },
                        new
                        {
                            Id = 51,
                            PhoneNumber = "1600090313499",
                            UserName = "Francis"
                        },
                        new
                        {
                            Id = 52,
                            PhoneNumber = "1664121873899",
                            UserName = "Amity"
                        },
                        new
                        {
                            Id = 53,
                            PhoneNumber = "1631081785199",
                            UserName = "Fletcher"
                        },
                        new
                        {
                            Id = 54,
                            PhoneNumber = "1633080375199",
                            UserName = "Murphy"
                        },
                        new
                        {
                            Id = 55,
                            PhoneNumber = "1602071238099",
                            UserName = "Hector"
                        },
                        new
                        {
                            Id = 56,
                            PhoneNumber = "1671031022599",
                            UserName = "Ignatius"
                        },
                        new
                        {
                            Id = 57,
                            PhoneNumber = "1698113007699",
                            UserName = "Warren"
                        },
                        new
                        {
                            Id = 58,
                            PhoneNumber = "1618031459799",
                            UserName = "Geraldine"
                        },
                        new
                        {
                            Id = 59,
                            PhoneNumber = "1621012650499",
                            UserName = "Idona"
                        },
                        new
                        {
                            Id = 60,
                            PhoneNumber = "1613080278199",
                            UserName = "Yvonne"
                        },
                        new
                        {
                            Id = 61,
                            PhoneNumber = "1647110243299",
                            UserName = "Samson"
                        },
                        new
                        {
                            Id = 62,
                            PhoneNumber = "1608040837199",
                            UserName = "Jana"
                        },
                        new
                        {
                            Id = 63,
                            PhoneNumber = "1657082432799",
                            UserName = "Wayne"
                        },
                        new
                        {
                            Id = 64,
                            PhoneNumber = "1613061721499",
                            UserName = "Kevin"
                        },
                        new
                        {
                            Id = 65,
                            PhoneNumber = "1616070115199",
                            UserName = "Flynn"
                        },
                        new
                        {
                            Id = 66,
                            PhoneNumber = "1683072514299",
                            UserName = "Herman"
                        },
                        new
                        {
                            Id = 67,
                            PhoneNumber = "1640060663599",
                            UserName = "Shelly"
                        },
                        new
                        {
                            Id = 68,
                            PhoneNumber = "1661061743199",
                            UserName = "Jonas"
                        },
                        new
                        {
                            Id = 69,
                            PhoneNumber = "1657012088699",
                            UserName = "Winifred"
                        },
                        new
                        {
                            Id = 70,
                            PhoneNumber = "1610092928999",
                            UserName = "Joy"
                        },
                        new
                        {
                            Id = 71,
                            PhoneNumber = "1668070850699",
                            UserName = "John"
                        },
                        new
                        {
                            Id = 72,
                            PhoneNumber = "1699101676899",
                            UserName = "Camilla"
                        },
                        new
                        {
                            Id = 73,
                            PhoneNumber = "1619051777299",
                            UserName = "Noelle"
                        },
                        new
                        {
                            Id = 74,
                            PhoneNumber = "1672112935399",
                            UserName = "Hollee"
                        },
                        new
                        {
                            Id = 75,
                            PhoneNumber = "1632011952199",
                            UserName = "Damon"
                        },
                        new
                        {
                            Id = 76,
                            PhoneNumber = "1684012416199",
                            UserName = "Axel"
                        },
                        new
                        {
                            Id = 77,
                            PhoneNumber = "1684031765599",
                            UserName = "Daphne"
                        },
                        new
                        {
                            Id = 78,
                            PhoneNumber = "1644022564499",
                            UserName = "Priscilla"
                        },
                        new
                        {
                            Id = 79,
                            PhoneNumber = "1643031564199",
                            UserName = "Tanisha"
                        },
                        new
                        {
                            Id = 80,
                            PhoneNumber = "1623040468499",
                            UserName = "Tarik"
                        },
                        new
                        {
                            Id = 81,
                            PhoneNumber = "1671081752999",
                            UserName = "Ali"
                        },
                        new
                        {
                            Id = 82,
                            PhoneNumber = "1618011374699",
                            UserName = "Azalia"
                        },
                        new
                        {
                            Id = 83,
                            PhoneNumber = "1656080825499",
                            UserName = "Derek"
                        },
                        new
                        {
                            Id = 84,
                            PhoneNumber = "1609112130399",
                            UserName = "Nissim"
                        },
                        new
                        {
                            Id = 85,
                            PhoneNumber = "1690082616299",
                            UserName = "Leslie"
                        },
                        new
                        {
                            Id = 86,
                            PhoneNumber = "1661112063799",
                            UserName = "Angela"
                        },
                        new
                        {
                            Id = 87,
                            PhoneNumber = "1692093071399",
                            UserName = "Tasha"
                        },
                        new
                        {
                            Id = 88,
                            PhoneNumber = "1650101035099",
                            UserName = "Daquan"
                        },
                        new
                        {
                            Id = 89,
                            PhoneNumber = "1649070570699",
                            UserName = "Jonah"
                        },
                        new
                        {
                            Id = 90,
                            PhoneNumber = "1636031208099",
                            UserName = "Robert"
                        },
                        new
                        {
                            Id = 91,
                            PhoneNumber = "1668060125399",
                            UserName = "Susan"
                        },
                        new
                        {
                            Id = 92,
                            PhoneNumber = "1692102894899",
                            UserName = "Orlando"
                        },
                        new
                        {
                            Id = 93,
                            PhoneNumber = "1663072384399",
                            UserName = "Daryl"
                        },
                        new
                        {
                            Id = 94,
                            PhoneNumber = "1613071180499",
                            UserName = "Baxter"
                        },
                        new
                        {
                            Id = 95,
                            PhoneNumber = "1607072647999",
                            UserName = "Plato"
                        },
                        new
                        {
                            Id = 96,
                            PhoneNumber = "1692041401399",
                            UserName = "Jenna"
                        },
                        new
                        {
                            Id = 97,
                            PhoneNumber = "1660060458099",
                            UserName = "Aretha"
                        },
                        new
                        {
                            Id = 98,
                            PhoneNumber = "1690102573499",
                            UserName = "Baxter"
                        },
                        new
                        {
                            Id = 99,
                            PhoneNumber = "1611121721399",
                            UserName = "Scarlett"
                        },
                        new
                        {
                            Id = 100,
                            PhoneNumber = "1614120347999",
                            UserName = "Althea"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
